// Game data migrated from Rails db/seeds.rb

export interface Item {
  id: number;
  name: string;
  isTakeable: boolean;
  description: string;
  inspectChoice1: string | null;
  inspectChoice2: string | null;
  isTalkable: boolean;
  talkResponse: string | null;
  talkChoice1: string | null;
  talkChoice2: string | null;
  isAttackable: boolean;
  attackResponse: string | null;
  catalystItem: number | null;
  catalystResponse: string | null;
  exitTrigger: boolean;
  triggersOn: string | null;
  deathTrigger: string | null;
  roomId: number;
}

export interface Room {
  id: number;
  name: string;
  description: string;
  deathThreshold: number;
  deathThresholdMet: string;
  introDescription: string;
}

export const rooms: Room[] = [
  {
    id: 1,
    name: 'Cell',
    description: 'Beneath you, you feel the silent hum of an engine; the floors and walls are made of metal, except for one wall which looks to be made of powerful Lasers. You appear to be in some sort of cell. Additionally, the room has one Window and there seems to be a man, perhaps your Cellmate, babbling to himself nearby.',
    deathThreshold: 5,
    deathThresholdMet: 'Two tall, grey, smooth aliens enter the room, one wearing a military-like garb and the other a lab coat. They are surprised to see you awake, but do not panic. The one in military garb points a small device at you, and you experience a quick shock followed by full-body-paralysis. They carry you through the alien ship and to a laboratory like room, where you are probed. You do not survive the process. You are dead.',
    introDescription: 'You open your eyes, awakening from a slumber. You feel groggy, and you do not recognize the place you are in. Your cellphone has no service. Beneath you, you feel the silent hum of an engine; the floors and walls are made of metal, except for one wall which looks to be made of powerful Lasers. You appear to be in some sort of cell. Additionally, the room has one Window and there seems to be a man, perhaps your Cellmate, babbling to himself nearby.',
  },
  {
    id: 2,
    name: 'Laboratory',
    description: "You find yourself in some sort of Laboratory--a dissected human Body is displayed on a surgical table next to a surgical Knife and other instruments. Nearby is a scientist's Desk and on it, a Computer. On the other end of the room, you see a device that resembles the classic Star Trek 'beam me up Scotty' Teleporter, with a blueprint of the ship on a screen.",
    deathThreshold: 10,
    deathThresholdMet: 'You hear a pounding on the door, followed by a long silence. Just as you think you are safe, the vents in the room let out a green gas, that, in addition to killing you, smells quite terrible.',
    introDescription: "You've escaped your cell, but hear the footsteps of more aliens quickly approaching. You open the door to the nearest room and shut the door behind you. You find yourself in some sort of Laboratory--a dissected human Body is displayed on a surgical table next to a surgical Knife and other instruments. Nearby is a scientist's Desk and on it, a Computer. On the other end of the room, you see a device that resembles the classic Star Trek 'beam me up Scotty' Teleporter, with a blueprint of the ship on a screen.",
  },
  {
    id: 3,
    name: 'Hallway',
    description: "You are in a hallway. The door to the ship's Escape Pods and Airlock is across from you, but blocked by a large number of the alien Crew. They have you surrounded in all directions. They are too numerous to fight off.",
    deathThreshold: 6,
    deathThresholdMet: "The alien Crew, with their laser eyes fixed on your position, await your surrender. After some time, they realize you have been stalling and their captain gives the order:\n'Fire.'\nThe aliens' eyes glow with a red intensity, and lasers shoot toward you. You are reduced to a pile of ash on the floor. You are put in a dustbin and placed in the garbage. You are dead.",
    introDescription: "You emerge from the Teleporter--the feeling of your molecules being disassembled and reassembled was unnerving but all things considered, quite seamless. You are in a hallway, and across from you is the door to the Escape Pods and Airlock. Standing between you and salvation, however, is a large number of the ship's alien Crew. One of them speaks to you:\n'You have done well to make it this far, human scum. But this is the end of the road for you. Surrender or die.",
  },
  {
    id: 4,
    name: 'Airlock',
    description: "You are at the entrance to the Airlock, located deep in the bowels of the ship. When activated, a large automatic door will open up to the vastness of space, sucking out anything not tied down. The doors are controlled by a Terminal next to the doors. This room also contains the Escape-Pods, with controls to launch them. An alien Engineer, who from her features seems to be a female, is waiting by the Escape-Pods with a package in hand.",
    deathThreshold: 15,
    deathThresholdMet: "A voice fills the room of the Airlock:\n'I know you are in there, human scum. You have killed dozens of my crew, and I will exact my revenge one hundred fold.\nThe humans of your planet will pay the price for your actions. You and the traitorous concubine Engineer will die in the cold.'\nThe sirens in the room activate, red lights flash and the doors to the Airlock begin to open. You are sucked into the vast emptiness of space.\nYou are dead. You will be Stuck in Space forever.",
    introDescription: "After activating your Watch gadget and burning out the eyes of the alien crew, you escape into the Airlock room. When you enter, you are startled by the presence of an alien woman, who seems to be the ship's Engineer, based on her jumpsuit and grease stains. The Airlock room contains a large automatic door that opens up to the vastness of space, sucking out anything not tied down. The door is controlled by a Terminal. This room also contains the Escape-Pods, with controls to launch them. You are so close to getting home.",
  },
  {
    id: 5,
    name: 'Blue Origin Space Cruise',
    description: "You are in the luxury ballroom of the Amazon Blue Origin space cruiser. A string quartet plays Schubert's 13th as the glamorous and beautiful celebrities mingle. The servants are hard at work, serving hors d'oeuvres on sterling silver plates and refilling wine glasses. You are greeted by Bezos, wearing a cowboy hat, but his Goons block your entrance to the ballroom.",
    deathThreshold: 10,
    deathThresholdMet: "Jeff Bezos grows agitated as he awaits your payment:\n'You know, I'd love to help you but... no free rides. It's the rules of the road: gas, grass or ass.'\nHe turns his head as he hears one of his celebrity friends call his name. You think that might have been Jay-Z's voice.\nHe snaps his fingers and his Amazon Goons grab you by the shoulders. They drag you toward the ship's Airlock and throw you in.\nThe doors open and you are sucked into space, where you die in the cold vastness of space. You are dead. You will be Stuck in Space forever.",
    introDescription: "You put on your Spacesuit and activate the ship's Airlock. You are sucked into space, and you can see the alien mothership drift by. After a few minutes, the mothership flies away, back to the alien homeworld. You have successfully escaped the aliens.\nBut now, you are alone, Stuck in Space. (That's the title of the game)\nYour odds of survival are low, and you float alone in space for many hours, your hope dwindling.\nMiraculously, a spaceship heading in the direction of Earth flies nearby. Through the cockpit windows you can see a man in a cowboy hat. It does not suit him.\nThe ship stops for you and picks you up. You are let in via the Airlock and walked through the cargo hold by workers wearing bright orange vests.\nYou are led to the stairs, and the orange vest workers tell you 'We cannot accompany you any further.'\nYou head up the stairs, and you find yourself in the luxury ballroom of the Amazon Blue Origin space cruiser. A string quartet plays Schubert's 13th as the glamorous and beautiful celebrities mingle. The servants are hard at work, serving hors d'oeuvres on sterling silver plates and refilling wine glasses. You are greeted by Bezos, wearing a cowboy hat, but his Goons block your entrance to the ballroom.",
  },
];

export const items: Item[] = [
  // Room 1: Cell
  {
    id: 1,
    name: 'Window',
    isTakeable: false,
    description: "You look out the window, and realize you are among the stars. You can still see Earth, and judging from its distance, you have not been on this ship long. If you haven't figured it out already, you are on a space ship. How you got here? That's for you to figure out.",
    inspectChoice1: null,
    inspectChoice2: null,
    isTalkable: false,
    talkResponse: null,
    talkChoice1: null,
    talkChoice2: null,
    isAttackable: true,
    attackResponse: 'You slam the window, but it is too sturdy to break... which is probably for the best, because if it did break, you would be pulled into the cold vacuum of space.',
    catalystItem: null,
    catalystResponse: null,
    exitTrigger: true,
    triggersOn: null,
    deathTrigger: null,
    roomId: 1,
  },
  {
    id: 2,
    name: 'Cellmate',
    isTakeable: false,
    description: 'The man in the room with you has grown out his hair and beard, and gives off a strong odor. He seems like he has been here for a while.',
    inspectChoice1: null,
    inspectChoice2: null,
    isTalkable: true,
    talkResponse: "'You're awake already? Most of the poor souls that I've shared this cell with are still asleep by now. Consider yourself unlucky, as you'll probably be awake through it all. ...Me? I got picked up a few weeks, months, maybe years ago. I've been told I'm not a 'proper specimen,' I'm too tight for the probe.\nAnyway, they'll be in here any minute now to drag you away.\nUnless...\nYou have any ideas? Between the two of us, there are plenty of classic 'break-out-of-jail' gambits we could pull.'\n1. Suggest he pretend to be sick-- you will call for help, and together you can overpower the guard.\n2. Suggest a fake prison fight-- you will hit him, and the guard will come break it up.",
    talkChoice1: "'My stomach! I'm backed up! I'm just too tight! Nothing gets through!' Weirdly specific, but if you call the guard, this will definitely distract him.",
    talkChoice2: "'It's been so long since I've felt anything that I welcome pain. Hit me as hard as you can, so I can feel the sublime ecstasy of pleasure. Go on, do it!'",
    isAttackable: true,
    attackResponse: "'My nose! You broke my goddamn nose! What is wrong with you?! Guard!!!' Blood flowing down his face, he calls for the guard: a tall, smooth, grey alien temporarily deactivates the laser wall with a Keycard and enters your cell. The Guard seems surprised to see you awake, so you have a chance to surprise him.",
    catalystItem: null,
    catalystResponse: null,
    exitTrigger: true,
    triggersOn: null,
    deathTrigger: null,
    roomId: 1,
  },
  {
    id: 3,
    name: 'Lasers',
    isTakeable: false,
    description: 'A blazing hot infrared laser wall, meant to keep you inside this cell. Anything that attempted to pass through it would likely be reduced to ashes.',
    inspectChoice1: null,
    inspectChoice2: null,
    isTalkable: true,
    talkResponse: 'You run up to the laser wall and call for help. Moments later, a tall, smooth, grey alien uses a Keycard to temporarily deactivate the laser wall and enters your cell. The Guard seems surprised to see you awake, so you have a chance to surprise him.',
    talkChoice1: null,
    talkChoice2: null,
    isAttackable: true,
    attackResponse: 'You attempt to punch the laser wall, and your entire arm is incinerated. You catch on fire and die.',
    catalystItem: 5,
    catalystResponse: 'You wave your Keycard at the Lasers, and they temporarily turn off. You may now EXIT the room freely.',
    exitTrigger: false,
    triggersOn: 'use',
    deathTrigger: 'attack',
    roomId: 1,
  },
  {
    id: 4,
    name: 'Guard',
    isTakeable: false,
    description: "A tall, smooth, grey alien. Pretty generic as far as aliens go. Don't feel bad about attacking him, because they abducted you and were going to probe you. Also, he's a prison guard. ACAB.",
    inspectChoice1: null,
    inspectChoice2: null,
    isTalkable: true,
    talkResponse: "You attempt to reason with the alien Guard. He seems to understand what you're saying-- perhaps these aliens have developed a universal translator. That being said, he does not seem particularly sympathetic to your situation. He shoots lasers from his eyes and you are burned alive. You die.",
    talkChoice1: null,
    talkChoice2: null,
    isAttackable: true,
    attackResponse: 'You punch the alien Guard in the face. Your fist tears through his soft, jelly-like flesh and you pulverize his brain. He falls dead to the floor and drops his Keycard. These aliens may look scary, but luckily for you, seem to be exceptionally weak.',
    catalystItem: null,
    catalystResponse: null,
    exitTrigger: false,
    triggersOn: 'attack',
    deathTrigger: 'talk',
    roomId: 1,
  },
  {
    id: 5,
    name: 'Keycard',
    isTakeable: true,
    description: 'A thin card held by the alien Guard. When waved at the laser wall, it lowers the Lasers and allows the holder to pass through.',
    inspectChoice1: null,
    inspectChoice2: null,
    isTalkable: false,
    talkResponse: null,
    talkChoice1: null,
    talkChoice2: null,
    isAttackable: false,
    attackResponse: null,
    catalystItem: null,
    catalystResponse: null,
    exitTrigger: false,
    triggersOn: 'take',
    deathTrigger: null,
    roomId: 1,
  },
  // Room 2: Laboratory
  {
    id: 6,
    name: 'Body',
    isTakeable: false,
    description: "The Body sprawled out on the table died with a smirk on his face, despite his cruel fate. His stomach has been cut open, and many organs have been removed. But even in this state, you can tell that this man was once quite handsome and, if you're checking, well-endowed. There seems to be something bulging out of a corner of his stomach.",
    inspectChoice1: null,
    inspectChoice2: null,
    isTalkable: true,
    talkResponse: 'You attempt to speak to the dead body, but there is no response. Not sure what you were expecting--a witty retort?',
    talkChoice1: null,
    talkChoice2: null,
    isAttackable: true,
    attackResponse: 'You attack the dead body. It does not fight back.',
    catalystItem: 7,
    catalystResponse: "You cut the body open with the surgical Knife, and inside of the body's stomach, discover a USB.",
    exitTrigger: true,
    triggersOn: '',
    deathTrigger: null,
    roomId: 2,
  },
  {
    id: 7,
    name: 'Knife',
    isTakeable: true,
    description: 'A surgical Knife, presumably used for dissections.',
    inspectChoice1: null,
    inspectChoice2: null,
    isTalkable: false,
    talkResponse: null,
    talkChoice1: null,
    talkChoice2: null,
    isAttackable: false,
    attackResponse: null,
    catalystItem: null,
    catalystResponse: null,
    exitTrigger: true,
    triggersOn: '',
    deathTrigger: null,
    roomId: 2,
  },
  {
    id: 8,
    name: 'USB',
    isTakeable: true,
    description: 'A USB-C drive, discovered hidden in the body of the dissected human. Why would it be there?',
    inspectChoice1: null,
    inspectChoice2: null,
    isTalkable: false,
    talkResponse: null,
    talkChoice1: null,
    talkChoice2: null,
    isAttackable: false,
    attackResponse: null,
    catalystItem: null,
    catalystResponse: null,
    exitTrigger: true,
    triggersOn: '',
    deathTrigger: null,
    roomId: 2,
  },
  {
    id: 9,
    name: 'Desk',
    isTakeable: false,
    description: "A Desk, made of a foreign alien metal. On top of it sits a Computer. There are a few empty drawers, and one locked drawer. You do not see a key for it anywhere nearby, but perhaps you could force it open.",
    inspectChoice1: null,
    inspectChoice2: null,
    isTalkable: false,
    talkResponse: null,
    talkChoice1: null,
    talkChoice2: null,
    isAttackable: true,
    attackResponse: 'You smash the Desk, and try to rip open the desk drawer. After a few attempts, you force it open. Inside, you see various valuables collected from dissected humans. Most notably, a Wallet and an Omega Watch.',
    catalystItem: 5,
    catalystResponse: "You wave the guard's Keycard near the locked drawer, and it pops open. Inside, you see various valuables collected from dissected humans. Most notably, a Wallet and an Omega Watch.",
    exitTrigger: true,
    triggersOn: '',
    deathTrigger: null,
    roomId: 2,
  },
  {
    id: 10,
    name: 'Watch',
    isTakeable: true,
    description: "A platinum Watch, very expensive, definitely out of your price range. It ticks and tells time, but seems to have a number of knobs and buttons whose functions you don't recognize.",
    inspectChoice1: null,
    inspectChoice2: null,
    isTalkable: false,
    talkResponse: null,
    talkChoice1: null,
    talkChoice2: null,
    isAttackable: false,
    attackResponse: null,
    catalystItem: null,
    catalystResponse: null,
    exitTrigger: true,
    triggersOn: '',
    deathTrigger: null,
    roomId: 2,
  },
  {
    id: 11,
    name: 'Wallet',
    isTakeable: true,
    description: 'A leather Wallet containing several passports with different identities, and £50,000 cash.',
    inspectChoice1: null,
    inspectChoice2: null,
    isTalkable: false,
    talkResponse: null,
    talkChoice1: null,
    talkChoice2: null,
    isAttackable: false,
    attackResponse: null,
    catalystItem: null,
    catalystResponse: null,
    exitTrigger: true,
    triggersOn: '',
    deathTrigger: null,
    roomId: 2,
  },
  {
    id: 12,
    name: 'Computer',
    isTakeable: false,
    description: 'An alien Computer, closely resembling the kind found on Earth. The information on the screen is in alien characters, so you cannot navigate through it. It does, weirdly enough, have a USB-C slot.',
    inspectChoice1: null,
    inspectChoice2: null,
    isTalkable: false,
    talkResponse: null,
    talkChoice1: null,
    talkChoice2: null,
    isAttackable: true,
    attackResponse: "You attack the computer. Yes, 'the files are in the computer', but that's not the way to get them out.",
    catalystItem: 8,
    catalystResponse: "You insert the USB-C drive into the Computer, and a message in English begins to display on the screen:\nBond,\nIf you're reading this message, the plan to have you abducted has gone swimmingly.\nI hope the USB drive didn't give you too much trouble coming out the other end.\nThe information from the alien Computer has been downloaded to this drive, which will give us a great advantage in preventing future abductions.\nYou have served Queen and Country again, now use the Teleporter and escape the ship. If you run into any of the buggers-- remember your Watch, it's quite an eyesore.\n\nGod speed, James.\n-Q",
    exitTrigger: true,
    triggersOn: '',
    deathTrigger: null,
    roomId: 2,
  },
  {
    id: 13,
    name: 'Teleporter',
    isTakeable: false,
    description: "The teleporter is an impressive piece of alien technology. A touch screen with a blueprint of the ship determines your destination, currently set to the Airlock and Escape Pods, conveniently for you. Inconvenient however-- the Teleporter seems to be on the fritz; sparks and static seem to be coming from the machine.\n1. Use the Teleporter\n2. Reconsider",
    inspectChoice1: "Hearing the steps of nearby aliens, you know you don't have time to worry about the state of the Teleporter. You hit the START button, ready to escape, but as it begins to whirr, smoke comes out of the machine and the machine reduces you to a pile of fleshy goop on the floor. You are dead.",
    inspectChoice2: 'You do not use the Teleporter. Is there a reliable, old fashioned way to get a complicated piece of tech working?',
    isTalkable: false,
    talkResponse: null,
    talkChoice1: null,
    talkChoice2: null,
    isAttackable: true,
    attackResponse: 'You smack the teleporter a few times, and all the sparks and static cease. It seems to be back to working perfectly. You may now EXIT the room.',
    catalystItem: 8,
    catalystResponse: 'You attempt to insert the USB-C drive into the Teleporter, but it only has USB-A and CD-ROM. Technology can be a pain in the butt.',
    exitTrigger: false,
    triggersOn: 'attack',
    deathTrigger: '1',
    roomId: 2,
  },
  {
    id: 15,
    name: 'Bowtie',
    isTakeable: true,
    description: 'A very classy black Bowtie, clearly belonging to a very classy man.',
    inspectChoice1: null,
    inspectChoice2: null,
    isTalkable: false,
    talkResponse: null,
    talkChoice1: null,
    talkChoice2: null,
    isAttackable: false,
    attackResponse: null,
    catalystItem: null,
    catalystResponse: null,
    exitTrigger: true,
    triggersOn: null,
    deathTrigger: null,
    roomId: 2,
  },
  // Room 3: Hallway
  {
    id: 14,
    name: 'Crew',
    isTakeable: false,
    description: "The alien Crew. Over a dozen-- they do not carry weapons but their eyes are glowing and fixed on your location. They have you surrounded in all directions, blocking your way to the ship's exit. They await your surrender.",
    inspectChoice1: null,
    inspectChoice2: null,
    isTalkable: true,
    talkResponse: "An alien speaks: 'There's no version of this where you make it out alive. Even if you had made it to the Escape Pods, our auto targeting system would blow you to pieces. Surrender or die, human scum. The road ends here. You are stuck in space.'\n1. Surrender to the aliens and accept the probe\n2. Make a defiant quip and buy yourself some time",
    talkChoice1: "'You've made a wise choice, human scum. The experiments we perform on your colon will lead to great innovations for our people.'\nAs the aliens accept your surrender, the glow in their eyes lessens. You may have bought yourself another moment.",
    talkChoice2: 'You search your mind for a moment, trying to think of the perfect quip. It is hard to be clever on demand.',
    isAttackable: true,
    attackResponse: "You punch the nearest alien in the face; your fist tears through his soft, jelly-like flesh. You swing on two more aliens, destroying them instantly. But there are still many to deal with and one alien gives the order: 'Fire.'\nThe alien Crew focuses on you with their glowing eyes, and they shoot red hot glowing lasers from their pupils. You are vaporized by the aliens' eye lasers. You are dead.",
    catalystItem: 10,
    catalystResponse: "You take out the Watch you found earlier, frantically turning dials and pushing buttons. The face of the Watch displays a message: 'Device Armed.'\nYou push down on the dial and a blinding white flash fills the room. Alien screams echo through the hallway, as their glowing eyes explode and set fire to the rest of their bodies. You think of the perfect quip: 'I thought you only had eyes for me.'\nEvery alien in sight is dead-- you may now EXIT the hallway and head for the Escape Pods and Airlock.",
    exitTrigger: false,
    triggersOn: 'use',
    deathTrigger: 'attack',
    roomId: 3,
  },
  // Room 4: Airlock
  {
    id: 16,
    name: 'Escape-Pods',
    isTakeable: false,
    description: "You walk up to the Escape Pods. A small rocketship with basic rudimentary controls. You believe this pod will be enough to get you back to Earth. If you take it, this could finally be the end of your odyssey.\n1. Get in the Escape Pod and launch it.\n2. Launch an empty Escape Pod into space.",
    inspectChoice1: "You get into the Escape Pod and launch yourself into space. You are able to figure out the basic controls and begin flying back toward Earth. As you finally exhale and feel safe, the sirens of your ship begin to flash and alarm. You look out the window of your ship and see a massive torpedo, fired from the alien mothership, heading in your direction. This is the last thing you see before you die.\n\nYou are dead.",
    inspectChoice2: 'To test the controls, or perhaps because you were feeling skittish, you launch an empty Escape Pod into space. And whether it was luck or foresight--you made the right decision. Seconds after the Escape Pod is launched, a torpedo from the alien mothership is launched and destroys the Escape Pod. They know that this is your way off the ship.',
    isTalkable: false,
    talkResponse: null,
    talkChoice1: null,
    talkChoice2: null,
    isAttackable: false,
    attackResponse: null,
    catalystItem: null,
    catalystResponse: null,
    exitTrigger: false,
    triggersOn: 'inspect',
    deathTrigger: '1',
    roomId: 4,
  },
  {
    id: 17,
    name: 'Engineer',
    isTakeable: false,
    description: "Judging from the difference in anatomical features, you surmise the alien Engineer to be the first alien woman you've seen on the ship. She is wearing a grease-covered jumpsuit and holding a wrapped package in her arms. She seemed to be watching the door expecting someone to arrive, but when it was you, her eyes filled with disappointment.",
    inspectChoice1: null,
    inspectChoice2: null,
    isTalkable: true,
    talkResponse: "The alien Engineer speaks English, but in an accent foreign to your world:\n'You aren't James. Where is he, human? Do you know him? He is a magnificent gentleman of class. Women want him and men want to be him. It was out of love and desire for him that I've betrayed my own kind to save yours. He told me to meet him here in the Airlock and aid in his escape. But it's you I see here now. And you're no James Bond.'\nYour chances of escaping this ship are slim without the help of the Engineer, and she is in no emotional state to assist you.\n1. Comfort the Engineer on her loss.\n2. Seduce the Engineer",
    talkChoice1: "You put your hand on the Engineer's shoulder and attempt to comfort her.\n'If only I had something to remember him by. He was such a classy man. A species that could produce a man so elegant does not deserve the cruel fate we have in store for Earth.'",
    talkChoice2: "You put your hand on the small of the Engineer's back and attempt to seduce her. She recoils.\n'Once you've eaten Zandarian Space Worm you don't want Gylorkian Sand Rat.' You don't exactly understand her metaphor but you get the gist.\nIs there a way to make yourself more classy and win the Engineer's love?",
    isAttackable: true,
    attackResponse: 'You punch the Engineer in the face. You were expecting her face to collapse like all the previous aliens, but instead it feels like you punched a steel wall. The Engineer pushes you into a wall and it feels like you have been hit by a truck. She grabs you and tosses you around the room like a piñata, slamming you against the walls and ceiling as you feel the life leave your body. You wish you knew that the women of this species have skin as hard as stone and the strength of ten humans. You are dead.',
    catalystItem: 15,
    catalystResponse: "You put on the classy Bowtie and approach the Engineer. Her eyes are filled with a healthy mixture of sadness and desire. She pulls you in, quite forcefully, and plants a kiss on your lips. Honestly, it feels kind of not-great.\n'Thank you, sexy Earth-man. You have reminded me of why I decided to save your species in the first place. The hot dudes.\nDo not take the Escape-Pods, the radar of the mothership will pick your presence up and destroy your ship imminently. Your best hope is to open the Airlock and float through space--you will be too small for our radar and with some luck, a human vessel will retrieve you.\nPlease take these items: a human Spacesuit, and my Authenticator, needed to access the Terminal and open the Airlock.\nMaybe one day, our people will be able to live in peace. And bang.",
    exitTrigger: false,
    triggersOn: 'use',
    deathTrigger: 'attack',
    roomId: 4,
  },
  {
    id: 18,
    name: 'Spacesuit',
    isTakeable: true,
    description: 'A spacesuit, made by the aliens but specifically tailored and specially rigged for a human body. Built for the body of a larger, more attractive man, but it will fit.',
    inspectChoice1: null,
    inspectChoice2: null,
    isTalkable: false,
    talkResponse: null,
    talkChoice1: null,
    talkChoice2: null,
    isAttackable: false,
    attackResponse: null,
    catalystItem: null,
    catalystResponse: null,
    exitTrigger: false,
    triggersOn: 'take',
    deathTrigger: null,
    roomId: 4,
  },
  {
    id: 19,
    name: 'Authenticator',
    isTakeable: true,
    description: "An alien Authenticator, a pocket-sized device that when waved in front of a locked Computer or Terminal, activates it with the owner's credentials.",
    inspectChoice1: null,
    inspectChoice2: null,
    isTalkable: false,
    talkResponse: null,
    talkChoice1: null,
    talkChoice2: null,
    isAttackable: false,
    attackResponse: null,
    catalystItem: null,
    catalystResponse: null,
    exitTrigger: false,
    triggersOn: 'take',
    deathTrigger: null,
    roomId: 4,
  },
  {
    id: 20,
    name: 'Terminal',
    isTakeable: false,
    description: 'A computer Terminal that controls the Airlock. It seems easy enough to operate, with OPEN and CLOSE buttons, but it seems to be locked behind a login.',
    inspectChoice1: null,
    inspectChoice2: null,
    isTalkable: false,
    talkResponse: null,
    talkChoice1: null,
    talkChoice2: null,
    isAttackable: false,
    attackResponse: null,
    catalystItem: 19,
    catalystResponse: "You wave the Authenticator in front of the Terminal, and the screen displays a message in the alien language. The Terminal's keyboard lights up, indicating it is ready to be activated and the Airlock doors can be opened.",
    exitTrigger: false,
    triggersOn: 'use',
    deathTrigger: null,
    roomId: 4,
  },
  {
    id: 21,
    name: 'Airlock',
    isTakeable: false,
    description: "A large blast door, controlled by a nearby Terminal. When opened, will expose the room to the void of space, sucking out everything not tied down. Without a proper space suit, opening the Airlock means the certainty of a cold death. With a proper space suit, opening the Airlock means the certain uncertainty of being alone in the vastness of space. The door seems to have a bit of rust sealing it shut--it clearly has not been used for some time.",
    inspectChoice1: null,
    inspectChoice2: null,
    isTalkable: false,
    talkResponse: null,
    talkChoice1: null,
    talkChoice2: null,
    isAttackable: true,
    attackResponse: 'You smash into the doors of the Airlock, and with each smash, you feel the hinges of the door loosening up and shedding the rust that binds it closed. After a few attempts, you feel confident that the Terminal will open the Airlock.',
    catalystItem: null,
    catalystResponse: null,
    exitTrigger: false,
    triggersOn: 'attack',
    deathTrigger: null,
    roomId: 4,
  },
  // Room 5: Blue Origin
  {
    id: 22,
    name: 'Bezos',
    isTakeable: false,
    description: 'Jeff Bezos, in all his glory. Bald, wearing a cowboy hat, totally ripped, and totally going through a mid-life crisis.',
    inspectChoice1: null,
    inspectChoice2: null,
    isTalkable: true,
    talkResponse: "Welcome to the Amazon Blue Origins Cruise Line! You're lucky we found you. I won't ask how you ended up here--but here's hoping it's because you're the lone survivor of a SpaceX rocket explosion.\nLet's get down to brass tax--this is our luxury liner, so I can't let you ride for free. I'd love to, I really would, but I have shareholders to answer to. It's my fiduciary responsibility to throw you out of the airlock if you can't pay.",
    talkChoice1: null,
    talkChoice2: null,
    isAttackable: true,
    attackResponse: "You punch Jeff Bezos in the face, living the dream of many across the world. It feels amazing. Unfortunately, Jeff Bezos is ripped now. In a blazing flash of Kung Fu, he attacks all of your body's pressure points and your heart stops.\n'I'll get your body home in 2 days or less. That's the Prime guarantee.'\nYou are dead.",
    catalystItem: 11,
    catalystResponse: "You hand Jeff Bezos the Wallet with £50,000 cash. He opens it up and thumbs through the money.\n'This is enough for your initial deposit. We will fly you home, and charge you the rest on your Amazon card.'\nBezos allows you in to the luxurious ballroom, where you socialize with all of Earth's most beautiful celebrities.\nYou have escaped the aliens, you are no longer stuck in space. When you return to Earth you will be very influential and wealthy.\nYou hear a voice, you think it's that of former president Barack Obama:\n'Now let me be clear--you've won the game. Hit EXIT to finish the game and view your high score on the leaderboard. God Bless America.'",
    exitTrigger: false,
    triggersOn: 'use',
    deathTrigger: 'attack',
    roomId: 5,
  },
];

// Helper to get items for a specific room
export function getItemsForRoom(roomId: number): Item[] {
  return items.filter(item => item.roomId === roomId);
}

// Helper to get a room by ID
export function getRoomById(roomId: number): Room | undefined {
  return rooms.find(room => room.id === roomId);
}

// Helper to get an item by ID
export function getItemById(itemId: number): Item | undefined {
  return items.find(item => item.id === itemId);
}

// Helper to get an item by name (case insensitive)
export function getItemByName(name: string, roomId: number): Item | undefined {
  return items.find(
    item => item.name.toLowerCase() === name.toLowerCase() && item.roomId === roomId
  );
}
